title: pip.wtf
description: Inline pip dependencies for small Python scripts.
show_downloads: true
plugins:
  - jekyll-remote-theme
remote_theme: sblisesivdin/biscuit
include:
  - README.md
  - favicon.png
